apiVersion: v1
kind: Pod
metadata:
  name: pod1
  labels:
    app: web

spec:
  containers:
    - image: yomna1267/img
      name: container1
      imagePullPolicy: IfNotPresent
      ports:
        - containerPort: 80